import { CharterBooking } from "@/app/home/bookings/types";

export const customerBookingFactory = (payload: any): CharterBooking => {
  return {
    id: payload?.id,
    price: payload?.price,
    metadata: {
      userId: payload?.metadata?.userId,
      orderId: payload?.metadata?.orderId,
      listingId: payload?.metadata?.listingId,
      paymentId: payload?.metadata?.paymentId,
      departureDate: payload?.metadata?.departureDate,
      charterProfileId: payload?.metadata?.charterProfileId,
      tripPrice: payload?.metadata?.tripPrice,
      bookedSeats: payload?.metadata?.bookedSeats,
      privateGuests: payload?.metadata?.privateGuests,
      payToTheCaptain: payload?.metadata?.payToTheCaptain,
      youPayToday: payload?.metadata?.youPayToday,
      bookedBy: payload?.metadata?.bookedBy,
      bookedByEmail: payload?.metadata?.bookedByEmail,
      comments: payload?.metadata?.comments,
      discountType: payload?.metadata?.discountType,
      isHandicap: payload?.metadata?.isHandicap,
      bidId: payload?.metadata?.bidId,
    },
    protected_metadata: payload?.protected_metadata,
    starts_at: payload?.starts_at,
    ends_at: payload?.ends_at,
    buffer_starts_at: payload?.buffer_starts_at,
    buffer_ends_at: payload?.buffer_ends_at,
    created_at: payload?.created_at,
    updated_at: payload?.updated_at,
    finalized_at: payload?.finalized_at,
    canceled_at: payload?.canceled_at,
    is_temporary: payload?.is_temporary,
    is_canceled: payload?.is_canceled,
    isICharterBid: payload?.isICharterBid,
    resource: {
      id: payload?.resource?.id,
      name: payload?.resource?.name,
      max_simultaneous_bookings: payload?.resource?.max_simultaneous_bookings,
      metadata: {
        listingId: payload?.resource?.metadata?.listingId,
        charterProfileId: payload?.resource?.metadata?.charterProfileId,
      },
      protected_metadata: payload?.resource?.protected_metadata,
      enabled: payload?.resource?.enabled,
      created_at: payload?.resource?.created_at,
      updated_at: payload?.resource?.updated_at,
    },
    listing: {
      id: payload?.listing?.id,
      experienceName: payload?.listing?.experienceName,
      experienceType: payload?.listing?.experienceType,
      captains: payload?.listing?.captains,
      description: payload?.listing?.description,
      isCompleted: payload?.listing?.isCompleted,
      isPublished: payload?.listing?.isPublished,
      isFinished: payload?.listing?.isFinished,
      resourceId: payload?.listing?.resourceId,
      serviceId: payload?.listing?.serviceId,
      scheduleId: payload?.listing?.scheduleId,
      createdAt: payload?.listing?.createdAt,
      boat: {
        id: payload?.listing?.boat?.id,
        boatType: payload?.listing?.boat?.boatType,
        boatDescription: payload?.listing?.boat?.boatDescription,
        guestCapacity: payload?.listing?.boat?.guestCapacity,
        duration: payload?.listing?.boat?.duration,
        seasonalExperience: payload?.listing?.boat?.seasonalExperience,
        facilities: payload?.listing?.boat?.facilities,
        availability: {
          mon: payload?.listing?.boat?.availability?.mon,
          tue: payload?.listing?.boat?.availability?.tue,
          wed: payload?.listing?.boat?.availability?.wed,
          thu: payload?.listing?.boat?.availability?.thu,
          fri: payload?.listing?.boat?.availability?.fri,
          sat: payload?.listing?.boat?.availability?.sat,
          sun: payload?.listing?.boat?.availability?.sun,
        },
        departureTime: {
          hour: payload?.listing?.boat?.departureTime?.hour,
          minute: payload?.listing?.boat?.departureTime?.minute,
        },
        isCompleted: payload?.listing?.boat?.isCompleted,
        createdAt: payload?.listing?.boat?.createdAt,
      },
      fishingExperience: {
        id: payload?.listing?.fishingExperience?.id,
        targetedSpecies: payload?.listing?.fishingExperience?.targetedSpecies,
        fishingTechniques:
          payload?.listing?.fishingExperience?.fishingTechniques,
        includedInPrice: payload?.listing?.fishingExperience?.includedInPrice,
        createdAt: payload?.listing?.fishingExperience?.createdAt,
        isCompleted: payload?.listing?.fishingExperience?.isCompleted,
      },
      pricingModel: {
        id: payload?.listing?.pricingModel?.id,
        type: payload?.listing?.pricingModel?.type,
        pricePerTrip: payload?.listing?.pricingModel?.pricePerTrip,
        specialDiscounts: {
          veteran: payload?.listing?.pricingModel?.specialDiscounts?.veteran,
          military: payload?.listing?.pricingModel?.specialDiscounts?.military,
          firstResponders:
            payload?.listing?.pricingModel?.specialDiscounts?.firstResponders,
        },
        paymentMethod: payload?.listing?.pricingModel?.paymentMethod,
        cancelationPolicy: payload?.listing?.pricingModel?.cancelationPolicy,
        hasIcharterBid: payload?.listing?.pricingModel?.hasIcharterBid,
        minBid: payload?.listing?.pricingModel?.minBid,
        maxBid: payload?.listing?.pricingModel?.maxBid,
        createdAt: payload?.listing?.pricingModel?.createdAt,
        isCompleted: payload?.listing?.fishingExperience?.isCompleted,
      },
      meetingPoint: {
        id: payload?.listing?.meetingPoint?.id,
        streetAddresss: payload?.listing?.meetingPoint?.streetAddresss,
        state: payload?.listing?.meetingPoint?.state,
        zipCode: payload?.listing?.meetingPoint?.zipCode,
        latitude: payload?.listing?.meetingPoint?.latitude,
        longitude: payload?.listing?.meetingPoint?.longitude,
        directions: payload?.listing?.meetingPoint?.directions,
        createdAt: payload?.listing?.meetingPoint?.createdAt,
        isCompleted: payload?.listing?.fishingExperience?.isCompleted,
      },
      charterProfile: {
        id: payload?.charterProfile?.id,
        email: payload?.charterProfile?.email,
        companyName: payload?.charterProfile?.companyName,
        captains: payload?.charterProfile?.captains,
        phoneNumber: payload?.charterProfile?.phoneNumber,
        yearsOfExperience: payload?.charterProfile?.yearsOfExperience,
        licensePDFUrl: payload?.charterProfile?.licensePDFUrl,
        location: payload?.charterProfile?.location,
        profilePictureUrl: payload?.charterProfile?.profilePictureUrl,
        nationality: payload?.charterProfile?.nationality,
        groups: payload?.charterProfile?.groups,
        createdAt: payload?.charterProfile?.createdAt,
        media: payload?.charterProfile?.media,
        instagram: payload.charterProfile.instagram || "",
        facebook: payload.charterProfile.facebook || "",
        tikTok: payload.charterProfile.tikTok || "",
        yelp: payload.charterProfile.yelp || "",
        rating: payload?.charterProfile?.rating,
        totalRatings: payload?.charterProfile?.totalRatings,
      },
    },
  };
};
